name: Python Code Quality
on: [ push ]
jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: uv lock
  linting:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: ./.github/actions/setup
      - run: uvx ruff check .
  formating:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .
  type-consistency:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: ./.github/actions/setup
      - run: uv run pyright .
  tests:
    runs-on: ubuntu-latest
    needs: [ lock_file ]
    steps:
      - uses: ./.github/actions/setup
      - run: uv run pytest -vv --durations=0 --cov
  build:
    runs-on: ubuntu-latest
    needs: [ linting, formating, type-consistency, tests ]
    steps:
      - uses: ./.github/actions/setup
      - run: uv run build
